server:
    port: 8080
spring:
  application:
    name: authen-service
    main:
      allow-circular-references: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  signerKey: "323efba8b6dea3819336c924735dd0517c46c6ee9df19d8d3c6f9ac2f6a4dfdc"
  valid-duration: 10 #in second
  refreshable-duration: 24 # in hours
