pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t authen-service:latest demo'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker rm -f authen-service || true
                docker run -d \
                  --name authen-service \
                  --network app-net \
                  -p 8080:8080 \
                  authen-service:latest
                '''
            }
        }
    }
}
